# Machine Learning: PyTorch

## Contents

- [Installation](#inst)
- [Getting Started: Automatic Differentiation](#start-auto)

## <a name="inst"></a>Installation 

In the web site https://pytorch.org/, there is a "Quick Start Locally" section. Choose your system and related options to get the instruction to install PyTorch.

For example, on a Windows machine without GPU that has Anaconda3 installed, the installation instruction is:

    conda install pytorch-cpu torchvision-cpu -c pytorch
    
On a Linux(Ubuntu) machine using pip and python3.6 without GPU, the installation instruction is:

    pip3 install https://download.pytorch.org/whl/cpu/torch-1.0.1.post2-cp36-cp36m-linux_x86_64.whl
    
    pip3 install torchvision


(Tutorial Materials from https://pytorch.org/tutorials/)

## <a name="start-auto"></a>Autograd: Automatic Differentiation

In [2]:
import torch

In [3]:
# Create a tensor and set requires_grad=True to track computation with it

x = torch.ones(2, 2, requires_grad=True)
print(x)



tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [4]:
# Do a tensor operation:

y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [5]:
# y was created as a result of an operation, so it has a grad_fn.

print(y.grad_fn)

In [6]:
#Do more operations on y

z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward1>)
