# Python Numerical Tools

## 1. numpy

(adapted from Scipy Org's numpy "Quickstart tutorial":
https://docs.scipy.org/doc/numpy/user/quickstart.html)

### Basics
#### An example

In [1]:
import numpy as np

In [2]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
a.shape

(3, 5)

In [5]:
a.ndim

2

In [10]:
a.dtype

dtype('int32')

In [11]:
a.dtype.name

'int32'

In [9]:
# the size in bytes of each element of the array
a.itemsize

4

In [8]:
a.size

15

In [12]:
type(a)

numpy.ndarray

In [13]:
b = np.array([6, 7, 8])
b

array([6, 7, 8])

In [14]:
type(b)

numpy.ndarray

#### Array Creation

In [16]:
# numpy array can be created from a regular Python list or tuple using the array function. 
# The type of the resulting array is deduced from the type of the elements in the sequences.
a = np.array((2,3,4))
a

array([2, 3, 4])

In [17]:
a.dtype

dtype('int32')

In [18]:
b = np.array([1.2, 3.5, 5.1])
b.dtype

dtype('float64')

In [20]:
# A frequent error consists in calling array with multiple numeric arguments, 
# rather than providing a single list of numbers as an argument.
a = np.array(1,2,3,4)    # ValueError

ValueError: only 2 non-keyword arguments accepted

In [21]:
# array transforms sequences of sequences into two-dimensional arrays, 
# sequences of sequences of sequences into three-dimensional arrays, and so on.
b = np.array([(1.5,2,3), (4,5,6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [22]:
# The type of the array can also be explicitly specified at creation time:
c = np.array( [ [1,2], [3,4] ], dtype=complex )
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [23]:
# NumPy offers several functions to create arrays with initial placeholder content. 
# These minimize the necessity of growing arrays, an expensive operation

# By default, the dtype of the created array is float64.
np.zeros( (3,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
np.ones( (2,3,4), dtype=np.int16 )                # dtype can also be specified

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [25]:
np.empty( (2,3) )                                 # uninitialized, output may vary

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [26]:
# To create sequences of numbers, NumPy provides a function analogous to range that returns arrays instead of lists.
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

In [27]:
np.arange( 0, 2, 0.3 )                 # it accepts float arguments

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [28]:
"""
When arange is used with floating point arguments, it is generally not possible to predict 
the number of elements obtained, due to the finite floating point precision. 
For this reason, it is usually better to use the function linspace that receives as an argument 
the number of elements that we want, instead of the step:
"""
np.linspace( 0, 2, 9 )                 # 9 numbers from 0 to 2

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [30]:
from numpy import pi
x = np.linspace( 0, 2*pi, 100 )        # useful to evaluate function at lots of points
f = np.sin(x)
f[90:]

array([-5.40640817e-01, -4.86196736e-01, -4.29794912e-01, -3.71662456e-01,
       -3.12033446e-01, -2.51147987e-01, -1.89251244e-01, -1.26592454e-01,
       -6.34239197e-02, -2.44929360e-16])

#### Printing Arrays

In [31]:
"""
When you print an array, NumPy displays it in a similar way to nested lists, but with the following layout:
the last axis is printed from left to right,
the second-to-last is printed from top to bottom,
the rest are also printed from top to bottom, with each slice separated from the next by an empty line.
One-dimensional arrays are then printed as rows, bidimensionals as matrices and tridimensionals as lists of matrices.
"""
a = np.arange(6)                         # 1d array
print(a)

[0 1 2 3 4 5]


In [32]:
np.arange(12).reshape(4,3)           # 2d array
print(b)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [33]:
c = np.arange(24).reshape(2,3,4)         # 3d array
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [39]:
# If an array is too large to be printed, NumPy automatically skips the central part of the array and only prints the corners:
print(np.arange(1600))

[   0    1    2 ... 1597 1598 1599]


In [40]:
print(np.arange(1600).reshape(40,40))

[[   0    1    2 ...   37   38   39]
 [  40   41   42 ...   77   78   79]
 [  80   81   82 ...  117  118  119]
 ...
 [1480 1481 1482 ... 1517 1518 1519]
 [1520 1521 1522 ... 1557 1558 1559]
 [1560 1561 1562 ... 1597 1598 1599]]


In [41]:
# To disable this behaviour and force NumPy to print the entire array, you can change the printing options using set_printoptions.
np.set_printoptions(threshold=np.nan)
print(np.arange(1600).reshape(40,40))

[[   0    1    2    3    4    5    6    7    8    9   10   11   12   13
    14   15   16   17   18   19   20   21   22   23   24   25   26   27
    28   29   30   31   32   33   34   35   36   37   38   39]
 [  40   41   42   43   44   45   46   47   48   49   50   51   52   53
    54   55   56   57   58   59   60   61   62   63   64   65   66   67
    68   69   70   71   72   73   74   75   76   77   78   79]
 [  80   81   82   83   84   85   86   87   88   89   90   91   92   93
    94   95   96   97   98   99  100  101  102  103  104  105  106  107
   108  109  110  111  112  113  114  115  116  117  118  119]
 [ 120  121  122  123  124  125  126  127  128  129  130  131  132  133
   134  135  136  137  138  139  140  141  142  143  144  145  146  147
   148  149  150  151  152  153  154  155  156  157  158  159]
 [ 160  161  162  163  164  165  166  167  168  169  170  171  172  173
   174  175  176  177  178  179  180  181  182  183  184  185  186  187
   188  189  190  191  192  

#### Basic Operations

In [42]:
# Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result.
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
c = a-b
c

array([20, 29, 38, 47])

In [43]:
b**2

array([0, 1, 4, 9], dtype=int32)

In [44]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [45]:
a<35

array([ True,  True, False, False])

In [46]:
# Unlike in many matrix languages, the product operator * operates elementwise in NumPy arrays. The matrix product can be performed using the @ operator (in python >=3.5) or the dot function or method:
A = np.array( [[1,1],
             [0,1]] )
B = np.array( [[2,0],
             [3,4]] )
A * B                       # elementwise product

array([[2, 0],
       [0, 4]])

In [47]:
A @ B                       # matrix product

array([[5, 4],
       [3, 4]])

In [48]:
A.dot(B)                    # another matrix product

array([[5, 4],
       [3, 4]])

In [49]:
# Some operations, such as += and *=, act in place to modify an existing array rather than create a new one.
a = np.ones((2,3), dtype=int)
b = np.random.random((2,3))
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [50]:
b += a
b

array([[3.42413012, 3.06457523, 3.94516152],
       [3.16436651, 3.65183554, 3.53624082]])

In [51]:
a += b                  # b is not automatically converted to integer type

TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

In [52]:
# When operating with arrays of different types, the type of the resulting array corresponds to the more general or precise one (a behavior known as upcasting).
a = np.ones(3, dtype=np.int32)
b = np.linspace(0,pi,3)
b.dtype.name

'float64'

In [53]:
c = a+b
c

array([1.        , 2.57079633, 4.14159265])

In [54]:
c.dtype.name

'float64'

In [56]:
d = np.exp(c*1j)
d.dtype.name

'complex128'

In [57]:
# Many unary operations, such as computing the sum of all the elements in the array, are implemented as methods of the ndarray class.
a = np.random.random((2,3))
a

array([[0.68183367, 0.38492218, 0.65490731],
       [0.73887591, 0.3667055 , 0.87385198]])

In [58]:
a.sum()

3.7010965509698632

In [59]:
a.min()

0.3667055042497177

In [60]:
a.max()

0.8738519789903887

In [61]:
# By default, these operations apply to the array as though it were a list of numbers, regardless of its shape. 
# However, by specifying the axis parameter you can apply an operation along the specified axis of an array:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [62]:
b.sum(axis=0)                            # sum of each column

array([12, 15, 18, 21])

In [63]:
b.min(axis=1)                            # min of each row

array([0, 4, 8])

In [64]:
b.cumsum(axis=1)                         # cumulative sum along each row

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

#### Universal Functions

In [65]:
# NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, 
# these are called “universal functions”(ufunc). Within NumPy, 
# these functions operate elementwise on an array, producing an array as output.
B = np.arange(3)
B

array([0, 1, 2])

In [66]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [67]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [68]:
C = np.array([2., -1., 4.])
np.add(B, C)

array([2., 0., 6.])

#### Indexing, Slicing and Iterating

In [69]:
# One-dimensional arrays can be indexed, sliced and iterated over, much like lists and other Python sequences.
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [70]:
a[2]

8

In [71]:
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [72]:
a[:6:2] = -1000    # equivalent to a[0:6:2] = -1000; from start to position 6, exclusive, set every 2nd element to -1000
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729], dtype=int32)

In [73]:
a[ : :-1]                                 # reversed a
for i in a:
     print(i**(1/3.))

nan
1.0
nan
3.0
nan
5.0
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


C:\Users\zhyin2\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in power
  This is separate from the ipykernel package so we can avoid doing imports until


In [74]:
# Multidimensional arrays can have one index per axis. These indices are given in a tuple separated by commas:
def f(x,y):
    return 10*x+y
b = np.fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [75]:
b[2,3]

23

In [76]:
b[0:5, 1]                       # each row in the second column of b

array([ 1, 11, 21, 31, 41])

In [77]:
b[ : ,1]                        # equivalent to the previous example

array([ 1, 11, 21, 31, 41])

In [78]:
b[1:3, : ]                      # each column in the second and third row of b

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [79]:
# When fewer indices are provided than the number of axes, the missing indices are considered complete slices:
b[-1]

array([40, 41, 42, 43])

In [80]:
# The expression within brackets in b[i] is treated as an i followed by as many instances of : as needed to represent the remaining axes.
# NumPy also allows you to write this using dots as b[i,...].
c = np.array( [[[  0,  1,  2],               # a 3D array (two stacked 2D arrays)
                [ 10, 12, 13]],
                [[100,101,102],
                [110,112,113]]])
c.shape
(2, 2, 3)

(2, 2, 3)

In [81]:
c[1,...]                                   # same as c[1,:,:] or c[1]

array([[100, 101, 102],
       [110, 112, 113]])

In [82]:
c[...,2]                                   # same as c[:,:,2]

array([[  2,  13],
       [102, 113]])

In [83]:
# Iterating over multidimensional arrays is done with respect to the first axis:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [84]:
# However, if one wants to perform an operation on each element in the array, 
# one can use the flat attribute which is an iterator over all the elements of the array:
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


### Shape Manipulation
#### Changing the shape of an array

In [86]:
# An array has a shape given by the number of elements along each axis:
a = np.floor(10*np.random.random((3,4)))
a

array([[4., 3., 7., 9.],
       [5., 7., 0., 7.],
       [4., 4., 0., 2.]])

In [87]:
a.shape

(3, 4)

In [93]:
# The shape of an array can be changed with various commands. 
# Note that the following three commands all return a modified array, but do not change the original array:

In [94]:
a.ravel()  # returns the array, flattened

array([4., 3., 7., 9., 5., 7., 0., 7., 4., 4., 0., 2.])

In [89]:
a.reshape(6,2)  # returns the array with a modified shape

array([[4., 3.],
       [7., 9.],
       [5., 7.],
       [0., 7.],
       [4., 4.],
       [0., 2.]])

In [90]:
a.T  # returns the array, transposed

array([[4., 5., 4.],
       [3., 7., 4.],
       [7., 0., 0.],
       [9., 7., 2.]])

In [92]:
print(a.T.shape, a.shape)

(4, 3) (3, 4)


In [96]:
"""
The order of the elements in the array resulting from ravel() is normally “C-style”, that is, 
the rightmost index “changes the fastest”, so the element after a[0,0] is a[0,1]. 
If the array is reshaped to some other shape, again the array is treated as “C-style”. 
NumPy normally creates arrays stored in this order, so ravel() will usually not need to 
copy its argument, but if the array was made by taking slices of another array 
or created with unusual options, it may need to be copied. 
The functions ravel() and reshape() can also be instructed, using an optional argument, 
to use FORTRAN-style arrays, in which the leftmost index changes the fastest.
"""

# The reshape function returns its argument with a modified shape, 
# whereas the ndarray.resize method modifies the array itself:
a

array([[4., 3., 7., 9.],
       [5., 7., 0., 7.],
       [4., 4., 0., 2.]])

In [97]:
a.resize((2,6))
a

array([[4., 3., 7., 9., 5., 7.],
       [0., 7., 4., 4., 0., 2.]])

In [98]:
# If a dimension is given as -1 in a reshaping operation, the other dimensions are automatically calculated:
a.reshape(3,-1)

array([[4., 3., 7., 9.],
       [5., 7., 0., 7.],
       [4., 4., 0., 2.]])

#### Stacking together different arrays

In [99]:
# Several arrays can be stacked together along different axes:
a = np.floor(10*np.random.random((2,2)))
a

array([[3., 9.],
       [7., 4.]])

In [100]:
b = np.floor(10*np.random.random((2,2)))
b

array([[2., 1.],
       [0., 2.]])

In [101]:
np.vstack((a,b))

array([[3., 9.],
       [7., 4.],
       [2., 1.],
       [0., 2.]])

In [102]:
np.hstack((a,b))

array([[3., 9., 2., 1.],
       [7., 4., 0., 2.]])

In [103]:
# The function column_stack stacks 1D arrays as columns into a 2D array. It is equivalent to hstack only for 2D arrays:
from numpy import newaxis
np.column_stack((a,b))     # with 2D arrays

array([[3., 9., 2., 1.],
       [7., 4., 0., 2.]])

In [104]:
a = np.array([4.,2.])
b = np.array([3.,8.])
np.column_stack((a,b))     # returns a 2D array

array([[4., 3.],
       [2., 8.]])

In [105]:
np.hstack((a,b))           # the result is different

array([4., 2., 3., 8.])

In [106]:
a[:,newaxis]               # this allows to have a 2D columns vector

array([[4.],
       [2.]])

In [107]:
np.column_stack((a[:,newaxis],b[:,newaxis]))

array([[4., 3.],
       [2., 8.]])

In [108]:
np.hstack((a[:,newaxis],b[:,newaxis]))   # the result is the same

array([[4., 3.],
       [2., 8.]])

In [110]:
"""
On the other hand, the function row_stack is equivalent to vstack for any input arrays. 
In general, for arrays of with more than two dimensions, hstack stacks along their second axes, 
vstack stacks along their first axes, and concatenate allows for an optional arguments 
giving the number of the axis along which the concatenation should happen.

Note, in complex cases, r_ and c_ are useful for creating arrays by stacking numbers along one axis. 
They allow the use of range literals (“:”)

When used with arrays as arguments, r_ and c_ are similar to vstack and hstack in their default behavior, 
but allow for an optional argument giving the number of the axis along which to concatenate.

"""
np.r_[1:4,0,4]

array([1, 2, 3, 0, 4])

#### Splitting one array into several smaller ones

In [111]:
"""
Using hsplit, you can split an array along its horizontal axis, either by specifying the number of 
equally shaped arrays to return, or by specifying the columns after which the division should occur:

vsplit splits along the vertical axis, and array_split allows one to specify along which axis to split.
"""
a = np.floor(10*np.random.random((2,12)))
a

array([[2., 3., 1., 6., 2., 1., 7., 3., 7., 6., 2., 3.],
       [2., 2., 6., 2., 2., 0., 4., 9., 0., 5., 4., 9.]])

In [112]:
np.hsplit(a,3)   # Split a into 3

[array([[2., 3., 1., 6.],
        [2., 2., 6., 2.]]), array([[2., 1., 7., 3.],
        [2., 0., 4., 9.]]), array([[7., 6., 2., 3.],
        [0., 5., 4., 9.]])]

In [113]:
np.hsplit(a,(3,4))   # Split a after the third and the fourth column

[array([[2., 3., 1.],
        [2., 2., 6.]]), array([[6.],
        [2.]]), array([[2., 1., 7., 3., 7., 6., 2., 3.],
        [2., 0., 4., 9., 0., 5., 4., 9.]])]

### Copies and Views

When operating and manipulating arrays, their data is sometimes copied into a new array and sometimes not. This is often a source of confusion for beginners. There are three cases:

#### No Copy at All

In [114]:
a = np.arange(12)
b = a            # no new object is created
b is a           # a and b are two names for the same ndarray object

True

In [115]:
b.shape = 3,4    # changes the shape of a
a.shape

(3, 4)

In [116]:
# Python passes mutable objects as references, so function calls make no copy.
def f(x):
    print(id(x))
id(a)                           # id is a unique identifier of an object

2299207959536

In [117]:
f(a)

2299207959536


#### View or Shallow Copy


In [118]:
# Different array objects can share the same data. The view method creates a new array object that looks at the same data.
c = a.view()
c is a

False

In [119]:
c.base is a                        # c is a view of the data owned by a

True

In [120]:
c.flags.owndata

False

In [122]:
c.shape = 2,6                      # a's shape doesn't change
a.shape

(3, 4)

In [123]:
c[0,4] = 1234                      # a's data changes
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [124]:
# Slicing an array returns a view of it:
s = a[ : , 1:3]     # spaces added for clarity; could also be written "s = a[:,1:3]"
s[:] = 10           # s[:] is a view of s. Note the difference between s=10 and s[:]=10
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

#### Deep Copy
The copy method makes a complete copy of the array and its data.

In [125]:
d = a.copy()                          # a new array object with new data is created
d is a

False

In [126]:
d.base is a                           # d doesn't share anything with a

False

In [127]:
d[0,0] = 9999
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

## Less Basic
### Broadcasting rules
Broadcasting allows universal functions to deal in a meaningful way with inputs that do not have exactly the same shape.

The first rule of broadcasting is that if all input arrays do not have the same number of dimensions, a “1” will be repeatedly prepended to the shapes of the smaller arrays until all the arrays have the same number of dimensions.

The second rule of broadcasting ensures that arrays with a size of 1 along a particular dimension act as if they had the size of the array with the largest shape along that dimension. The value of the array element is assumed to be the same along that dimension for the “broadcast” array.

After application of the broadcasting rules, the sizes of all arrays must match.

### Fancy indexing and index tricks

NumPy offers more indexing facilities than regular Python sequences. In addition to indexing by integers and slices, as we saw before, arrays can be indexed by arrays of integers and arrays of booleans.

#### Indexing with Arrays of Indices

In [132]:
a = np.arange(12)**2                       # the first 12 square numbers
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121],
      dtype=int32)

In [133]:
i = np.array( [ 1,1,3,8,5 ] )              # an array of indices
a[i]                                       # the elements of a at the positions i

array([ 1,  1,  9, 64, 25], dtype=int32)

In [130]:
j = np.array( [ [ 3, 4], [ 9, 7 ] ] )      # a bidimensional array of indices
a[j]

array([[ 9, 16],
       [81, 49]], dtype=int32)

In [135]:
# When the indexed array a is multidimensional, a single array of indices refers to the first dimension of a. The following example shows this behavior by converting an image of labels into a color image using a palette.
palette = np.array( [ [0,0,0],               # black
                     [255,0,0],              # red
                     [0,255,0],              # green
                     [0,0,255],              # blue
                     [255,255,255] ] )       # white
image = np.array( [ [ 0, 1, 2, 0 ],           # each value corresponds to a color in the palette
                    [ 0, 3, 4, 0 ]  ] )
palette[image]                            # the (2,4,3) color image

array([[[  0,   0,   0],
        [255,   0,   0],
        [  0, 255,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0, 255],
        [255, 255, 255],
        [  0,   0,   0]]])

In [136]:
# We can also give indexes for more than one dimension. The arrays of indices for each dimension must have the same shape.
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [137]:
i = np.array( [ [0,1],                        # indices for the first dim of a
               [1,2] ] )
j = np.array( [ [2,1],                        # indices for the second dim
               [3,3] ] )
a[i,j]                                     # i and j must have equal shape

array([[ 2,  5],
       [ 7, 11]])

In [138]:
a[i,2]

array([[ 2,  6],
       [ 6, 10]])

In [139]:
a[:,j]                              

array([[[ 2,  1],
        [ 3,  3]],

       [[ 6,  5],
        [ 7,  7]],

       [[10,  9],
        [11, 11]]])

In [141]:
# Naturally, we can put i and j in a sequence (say a list) and then do the indexing with the list.
l = (i,j)
a[l]                                       # equivalent to a[i,j]

array([[ 2,  5],
       [ 7, 11]])

In [142]:
# However, we can not do this by putting i and j into an array, 
# because this array will be interpreted as indexing the first dimension of a.
s = np.array( [i,j] )
a[s]                                       # not what we want

IndexError: index 3 is out of bounds for axis 0 with size 3

In [143]:
a[tuple(s)]                                # same as a[i,j]

array([[ 2,  5],
       [ 7, 11]])

In [144]:
# Another common use of indexing with arrays is the search of the maximum value of time-dependent series:
time = np.linspace(20, 145, 5)                 # time scale
time

array([ 20.  ,  51.25,  82.5 , 113.75, 145.  ])

In [145]:
data = np.sin(np.arange(20)).reshape(5,4)      # 4 time-dependent series
data

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021],
       [-0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721]])

In [146]:
ind = data.argmax(axis=0)                  # index of the maxima for each series
ind

array([2, 0, 3, 1], dtype=int64)

In [147]:
time_max = time[ind]                       # times corresponding to the maxima
time_max

array([ 82.5 ,  20.  , 113.75,  51.25])

In [148]:
data_max = data[ind, range(data.shape[1])] # => data[ind[0],0], data[ind[1],1]...
data_max

array([0.98935825, 0.84147098, 0.99060736, 0.6569866 ])

In [149]:
np.all(data_max == data.max(axis=0))

True

In [150]:
# You can also use indexing with arrays as a target to assign to:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [151]:
a[[1,3,4]] = 0
a

array([0, 0, 2, 0, 0])

In [152]:
# However, when the list of indices contains repetitions, the assignment is done several times, leaving behind the last value:
a = np.arange(5)
a[[0,0,2]]=[1,2,3]
a

array([2, 1, 3, 3, 4])

In [154]:
# This is reasonable enough, but watch out if you want to use Python’s += construct, as it may not do what you expect:
a = np.arange(5)
a[[0,0,2]] += 1
a

array([1, 1, 3, 3, 4])

In [155]:
# Even though 0 occurs twice in the list of indices, the 0th element is only incremented once.

#### Indexing with Boolean Arrays
When we index arrays with arrays of (integer) indices we are providing the list of indices to pick. With boolean indices the approach is different; we explicitly choose which items in the array we want and which ones we don’t.

The most natural way one can think of for boolean indexing is to use boolean arrays that have the same shape as the original array:

In [156]:
a = np.arange(12).reshape(3,4)
b = a > 4
b                                          # b is a boolean with a's shape

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [157]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [158]:
# This property can be very useful in assignments:
a[b] = 0                                   # All elements of 'a' higher than 4 become 0
a

array([[0, 1, 2, 3],
       [4, 0, 0, 0],
       [0, 0, 0, 0]])

In [163]:
# The second way of indexing with booleans is more similar to integer indexing; 
# for each dimension of the array we give a 1D boolean array selecting the slices we want:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [164]:
b1 = np.array([False,True,True])             # first dim selection
b2 = np.array([True,False,True,False])       # second dim selection
a[b1,:]                                   # selecting rows

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [160]:
a[b1]                                     # same thing

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [161]:
a[:,b2]                                   # selecting columns

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [165]:
a[b1,b2]                                  # a weird thing to do

array([ 4, 10])

In [166]:
# Note that the length of the 1D boolean array must coincide with the length of the dimension (or axis) you want to slice. 
# In the previous example, b1 has length 3 (the number of rows in a), 
# and b2 (of length 4) is suitable to index the 2nd axis (columns) of a.

### Linear Algebra
Basic linear algebra

In [168]:
a = np.array([[1.0, 2.0], [3.0, 4.0]])
print(a)

[[1. 2.]
 [3. 4.]]


In [169]:
a.transpose()

array([[1., 3.],
       [2., 4.]])

In [170]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [171]:
u = np.eye(2) # unit 2x2 matrix; "eye" represents "I"
u

array([[1., 0.],
       [0., 1.]])

In [172]:
j = np.array([[0.0, -1.0], [1.0, 0.0]])
j @ j        # matrix product

array([[-1.,  0.],
       [ 0., -1.]])

In [173]:
np.trace(u)  # trace

2.0

In [174]:
y = np.array([[5.], [7.]])
np.linalg.solve(a, y)

array([[-3.],
       [ 4.]])

In [175]:
np.linalg.eig(j)

(array([0.+1.j, 0.-1.j]),
 array([[0.70710678+0.j        , 0.70710678-0.j        ],
        [0.        -0.70710678j, 0.        +0.70710678j]]))

Parameters:

    square matrix
    
Returns

    The eigenvalues, each repeated according to its multiplicity.
    
    The normalized (unit "length") eigenvectors, such that the column ``v[:,i]`` is the eigenvector corresponding to the eigenvalue ``w[i]`` .