# Python Numerical Tools

## 1. numpy

(adapted from Scipy Org's numpy "Quickstart tutorial":
https://docs.scipy.org/doc/numpy/user/quickstart.html)

### Basics
#### An example

In [1]:
import numpy as np

In [2]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
a.shape

(3, 5)

In [5]:
a.ndim

2

In [10]:
a.dtype

dtype('int32')

In [11]:
a.dtype.name

'int32'

In [9]:
# the size in bytes of each element of the array
a.itemsize

4

In [8]:
a.size

15

In [12]:
type(a)

numpy.ndarray

In [13]:
b = np.array([6, 7, 8])
b

array([6, 7, 8])

In [14]:
type(b)

numpy.ndarray

#### Array Creation

In [16]:
# numpy array can be created from a regular Python list or tuple using the array function. 
# The type of the resulting array is deduced from the type of the elements in the sequences.
a = np.array((2,3,4))
a

array([2, 3, 4])

In [17]:
a.dtype

dtype('int32')

In [18]:
b = np.array([1.2, 3.5, 5.1])
b.dtype

dtype('float64')

In [20]:
# A frequent error consists in calling array with multiple numeric arguments, 
# rather than providing a single list of numbers as an argument.
a = np.array(1,2,3,4)    # ValueError

ValueError: only 2 non-keyword arguments accepted

In [21]:
# array transforms sequences of sequences into two-dimensional arrays, 
# sequences of sequences of sequences into three-dimensional arrays, and so on.
b = np.array([(1.5,2,3), (4,5,6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [22]:
# The type of the array can also be explicitly specified at creation time:
c = np.array( [ [1,2], [3,4] ], dtype=complex )
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [23]:
# NumPy offers several functions to create arrays with initial placeholder content. 
# These minimize the necessity of growing arrays, an expensive operation

# By default, the dtype of the created array is float64.
np.zeros( (3,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
np.ones( (2,3,4), dtype=np.int16 )                # dtype can also be specified

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [25]:
np.empty( (2,3) )                                 # uninitialized, output may vary

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [26]:
# To create sequences of numbers, NumPy provides a function analogous to range that returns arrays instead of lists.
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

In [27]:
np.arange( 0, 2, 0.3 )                 # it accepts float arguments

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [28]:
"""
When arange is used with floating point arguments, it is generally not possible to predict 
the number of elements obtained, due to the finite floating point precision. 
For this reason, it is usually better to use the function linspace that receives as an argument 
the number of elements that we want, instead of the step:
"""
np.linspace( 0, 2, 9 )                 # 9 numbers from 0 to 2

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [30]:
from numpy import pi
x = np.linspace( 0, 2*pi, 100 )        # useful to evaluate function at lots of points
f = np.sin(x)
f[90:]

array([-5.40640817e-01, -4.86196736e-01, -4.29794912e-01, -3.71662456e-01,
       -3.12033446e-01, -2.51147987e-01, -1.89251244e-01, -1.26592454e-01,
       -6.34239197e-02, -2.44929360e-16])

#### Printing Arrays

In [31]:
"""
When you print an array, NumPy displays it in a similar way to nested lists, but with the following layout:
the last axis is printed from left to right,
the second-to-last is printed from top to bottom,
the rest are also printed from top to bottom, with each slice separated from the next by an empty line.
One-dimensional arrays are then printed as rows, bidimensionals as matrices and tridimensionals as lists of matrices.
"""
a = np.arange(6)                         # 1d array
print(a)

[0 1 2 3 4 5]


In [32]:
np.arange(12).reshape(4,3)           # 2d array
print(b)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [33]:
c = np.arange(24).reshape(2,3,4)         # 3d array
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [39]:
# If an array is too large to be printed, NumPy automatically skips the central part of the array and only prints the corners:
print(np.arange(1600))

[   0    1    2 ... 1597 1598 1599]


In [40]:
print(np.arange(1600).reshape(40,40))

[[   0    1    2 ...   37   38   39]
 [  40   41   42 ...   77   78   79]
 [  80   81   82 ...  117  118  119]
 ...
 [1480 1481 1482 ... 1517 1518 1519]
 [1520 1521 1522 ... 1557 1558 1559]
 [1560 1561 1562 ... 1597 1598 1599]]


In [41]:
# To disable this behaviour and force NumPy to print the entire array, you can change the printing options using set_printoptions.
np.set_printoptions(threshold=np.nan)
print(np.arange(1600).reshape(40,40))

[[   0    1    2    3    4    5    6    7    8    9   10   11   12   13
    14   15   16   17   18   19   20   21   22   23   24   25   26   27
    28   29   30   31   32   33   34   35   36   37   38   39]
 [  40   41   42   43   44   45   46   47   48   49   50   51   52   53
    54   55   56   57   58   59   60   61   62   63   64   65   66   67
    68   69   70   71   72   73   74   75   76   77   78   79]
 [  80   81   82   83   84   85   86   87   88   89   90   91   92   93
    94   95   96   97   98   99  100  101  102  103  104  105  106  107
   108  109  110  111  112  113  114  115  116  117  118  119]
 [ 120  121  122  123  124  125  126  127  128  129  130  131  132  133
   134  135  136  137  138  139  140  141  142  143  144  145  146  147
   148  149  150  151  152  153  154  155  156  157  158  159]
 [ 160  161  162  163  164  165  166  167  168  169  170  171  172  173
   174  175  176  177  178  179  180  181  182  183  184  185  186  187
   188  189  190  191  192  

#### Basic Operations

In [42]:
# Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result.
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
c = a-b
c

array([20, 29, 38, 47])

In [43]:
b**2

array([0, 1, 4, 9], dtype=int32)

In [44]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [45]:
a<35

array([ True,  True, False, False])

In [46]:
# Unlike in many matrix languages, the product operator * operates elementwise in NumPy arrays. The matrix product can be performed using the @ operator (in python >=3.5) or the dot function or method:
A = np.array( [[1,1],
             [0,1]] )
B = np.array( [[2,0],
             [3,4]] )
A * B                       # elementwise product

array([[2, 0],
       [0, 4]])

In [47]:
A @ B                       # matrix product

array([[5, 4],
       [3, 4]])

In [48]:
A.dot(B)                    # another matrix product

array([[5, 4],
       [3, 4]])

In [49]:
# Some operations, such as += and *=, act in place to modify an existing array rather than create a new one.
a = np.ones((2,3), dtype=int)
b = np.random.random((2,3))
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [50]:
b += a
b

array([[3.42413012, 3.06457523, 3.94516152],
       [3.16436651, 3.65183554, 3.53624082]])

In [51]:
a += b                  # b is not automatically converted to integer type

TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

In [52]:
# When operating with arrays of different types, the type of the resulting array corresponds to the more general or precise one (a behavior known as upcasting).
a = np.ones(3, dtype=np.int32)
b = np.linspace(0,pi,3)
b.dtype.name

'float64'

In [53]:
c = a+b
c

array([1.        , 2.57079633, 4.14159265])

In [54]:
c.dtype.name

'float64'

In [56]:
d = np.exp(c*1j)
d.dtype.name

'complex128'

In [57]:
# Many unary operations, such as computing the sum of all the elements in the array, are implemented as methods of the ndarray class.
a = np.random.random((2,3))
a

array([[0.68183367, 0.38492218, 0.65490731],
       [0.73887591, 0.3667055 , 0.87385198]])

In [58]:
a.sum()

3.7010965509698632

In [59]:
a.min()

0.3667055042497177

In [60]:
a.max()

0.8738519789903887

In [61]:
# By default, these operations apply to the array as though it were a list of numbers, regardless of its shape. 
# However, by specifying the axis parameter you can apply an operation along the specified axis of an array:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [62]:
b.sum(axis=0)                            # sum of each column

array([12, 15, 18, 21])

In [63]:
b.min(axis=1)                            # min of each row

array([0, 4, 8])

In [64]:
b.cumsum(axis=1)                         # cumulative sum along each row

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

#### Universal Functions

In [65]:
# NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, 
# these are called “universal functions”(ufunc). Within NumPy, 
# these functions operate elementwise on an array, producing an array as output.
B = np.arange(3)
B

array([0, 1, 2])

In [66]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [67]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [68]:
C = np.array([2., -1., 4.])
np.add(B, C)

array([2., 0., 6.])

#### Indexing, Slicing and Iterating

In [69]:
# One-dimensional arrays can be indexed, sliced and iterated over, much like lists and other Python sequences.
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [70]:
a[2]

8

In [71]:
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [72]:
a[:6:2] = -1000    # equivalent to a[0:6:2] = -1000; from start to position 6, exclusive, set every 2nd element to -1000
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729], dtype=int32)

In [73]:
a[ : :-1]                                 # reversed a
for i in a:
     print(i**(1/3.))

nan
1.0
nan
3.0
nan
5.0
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


C:\Users\zhyin2\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in power
  This is separate from the ipykernel package so we can avoid doing imports until


In [74]:
# Multidimensional arrays can have one index per axis. These indices are given in a tuple separated by commas:
def f(x,y):
    return 10*x+y
b = np.fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [75]:
b[2,3]

23

In [76]:
b[0:5, 1]                       # each row in the second column of b

array([ 1, 11, 21, 31, 41])

In [77]:
b[ : ,1]                        # equivalent to the previous example

array([ 1, 11, 21, 31, 41])

In [78]:
b[1:3, : ]                      # each column in the second and third row of b

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [79]:
# When fewer indices are provided than the number of axes, the missing indices are considered complete slices:
b[-1]

array([40, 41, 42, 43])

In [80]:
# The expression within brackets in b[i] is treated as an i followed by as many instances of : as needed to represent the remaining axes.
# NumPy also allows you to write this using dots as b[i,...].
c = np.array( [[[  0,  1,  2],               # a 3D array (two stacked 2D arrays)
                [ 10, 12, 13]],
                [[100,101,102],
                [110,112,113]]])
c.shape
(2, 2, 3)

(2, 2, 3)

In [81]:
c[1,...]                                   # same as c[1,:,:] or c[1]

array([[100, 101, 102],
       [110, 112, 113]])

In [82]:
c[...,2]                                   # same as c[:,:,2]

array([[  2,  13],
       [102, 113]])

In [83]:
# Iterating over multidimensional arrays is done with respect to the first axis:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [84]:
# However, if one wants to perform an operation on each element in the array, 
# one can use the flat attribute which is an iterator over all the elements of the array:
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


### Shape Manipulation
#### Changing the shape of an array